# Generated by Django 6.0.3 on 2026-03-28 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut_prevue', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_debut_reelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('non_demarree', 'Non démarrée'), ('en_cours', 'En cours'), ('completee', 'Complétée'), ('suspendue', 'Suspendue')], default='non_demarree', max_length=20)),
                ('pourcentage_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resultats_attendus', models.TextField(blank=True)),
                ('resultats_realises', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['projet', 'date_debut_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('personnel', 'Personnel'), ('equipement', 'Équipement'), ('infrastructure', 'Infrastructure'), ('transport', 'Transport'), ('fournitures', 'Fournitures'), ('formation', 'Formation'), ('audit', 'Audit'), ('autre', 'Autre')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_depense', models.DateField()),
                ('beneficiaire', models.CharField(blank=True, max_length=255)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_financement', models.CharField(choices=[('gouvernement', 'Gouvernement RDC'), ('banque_developpement', 'Banque de développement'), ('ong', 'ONG / Organisation internationale'), ('secteur_prive', 'Secteur privé'), ('partenaire', 'Partenaire bilatéral'), ('autre', 'Autre')], max_length=30)),
                ('nom_financeur', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_accord', models.DateField()),
                ('date_versement_prevue', models.DateField()),
                ('date_versement_reelle', models.DateField(blank=True, null=True)),
                ('statut_versement', models.CharField(choices=[('prevu', 'Prévu'), ('verse', 'Versé'), ('retard', 'En retard'), ('annule', 'Annulé')], default='prevu', max_length=20)),
                ('reference_accord', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financement',
                'verbose_name_plural': 'Financements',
                'ordering': ['projet', '-date_accord'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_projet', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('objectif', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_finance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('devise', models.CharField(default='CDF', max_length=3)),
                ('province', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('zone_geographique', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_rapport', models.CharField(choices=[('trimestri', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel'), ('final', 'Final'), ('audit', 'Audit')], max_length=20)),
                ('date_rapport', models.DateField()),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_rapport'],
            },
        ),
    ]
