# Generated by Django 6.0.3 on 2026-03-28 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_createurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projet',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financement',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financements', to='projets.projet'),
        ),
        migrations.AddField(
            model_name='depense',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='projets.projet'),
        ),
        migrations.AddField(
            model_name='activite',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='projets.projet'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_approuves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='projets.projet'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='redacteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_rediges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='financement',
            unique_together={('projet', 'nom_financeur')},
        ),
    ]
